### ISSUE TITLE
External code can't access Consume fields, and thus can't implement Consumer

### ISSUE THREAD

**Issue by daboross** [jonas-schievink/rubble#145]
I ran into this when copying over the implementation from #137 into a crate outside of `rubble` - it looks like `Consume`, the type used for conveying results to `Consumer`, has private fields only accessible to rubble. Unless I'm missing a way to get into `Consume::consume` and `Consume::result`, this prevents outside users from implementing queues built to their needs.

I think this could be fixed pretty easily by either making fields public (maybe with an adding private `()` field for forward compatibility), or by adding accessors. If it's alright, I'll submit a PR - I mildly favor accessors, but since rubble's still pre-`1.0`, and `Consume` is fairly feature-complete for what it is, it probably doesn't matter a ton?

**Comment by jonas-schievink** [comment]
Oof, yeah, feel free to add accessors.

**Comment by daboross** [comment]
Will do then. Filed #148!
