### ISSUE TITLE
P-256 cryptography support

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/rubble#40]
For pairing, we need to perform ECDH on P-256. [ring](https://github.com/briansmith/ring) can provide that, but unfortunately does not currently build on thumb targets. We need to fix that or use a different library that provides P-256 operations.

**Comment by jonas-schievink** [comment]
Blocked on https://github.com/briansmith/ring/issues/813

https://github.com/briansmith/ring/issues/744 also contains relevant discussion.

**Comment by briansmith** [comment]
FYI, https://github.com/briansmith/ring/pull/1011 will add support for P-256 for more targets.
