### ISSUE TITLE
Make rubble-nrf52810 support all nRF52 chips

### ISSUE THREAD

**Issue by jonas-schievink** [jonas-schievink/rubble#51]
The nRF52 chips are very similar (except the nRF52840, which has additional features for ZigBee and Thread - it should still work similarly though), so we should try to make the existing `rubble-nrf52810` crate work with all of them.

The best way to do this is probably by renaming `rubble-nrf52810` to `rubble-nrf52` and then using Cargo features and `#[cfg]` to select a chip, similar to what the `nrf52-hal-common` crate does.

**Comment by chocol4te** [comment]
Would now also be the time to make a `rubble-nrf51` crate?

**Comment by jonas-schievink** [comment]
That requires https://github.com/jonas-schievink/rubble/issues/25, so the crate wouldn't compile right now

**Comment by chocol4te** [comment]
🤦‍♂️ I forgot about that :/

**Comment by jonas-schievink** [comment]
Fixed by https://github.com/jonas-schievink/rubble/pull/54
