### ISSUE TITLE
tx_payload_buf problem

### ISSUE THREAD

**Issue by thalesfragoso** [jonas-schievink/rubble#67]
Shouldn't this method check for ongoing transactions before handing out the buffer ?
~~Also, shouldn't the radio driver for the nrf-52 have some compiler-fences for the DMA ?~~

**Comment by jonas-schievink** [comment]
Thanks for the report! This does indeed look unsound.

> Shouldn't this method check for ongoing transactions before handing out the buffer ?

Yes, it should. I believe we used to block until the end of transmission in `transmit_data`, so this wasn't able to cause problems before.

>  Also, shouldn't the radio driver for the nrf-52 have some compiler-fences for the DMA ?

Probably, yeah. The nRF52 HAL has [this setup](https://github.com/nrf-rs/nrf52-hal/blob/b5e76b07707395c9503fadd8b32e2b1d1c155ed1/nrf52-hal-common/src/twim.rs#L103-L153) around DMA transfers, so we should probably try to copy that.

Feel free to send a fix if you want to.
